//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonSerializer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> BookId { get; set; }
    }
}
